### ISSUE TITLE
chrome throws "Error in event handler: Error: write after end"

### ISSUE THREAD

**Issue by mdo6180** [anacostiaAI/anacostia-pipeline#21]
- happens when pulling up filesystemstore node on the frontend.

**Comment by mdo6180** [comment]
> Error in event handler: Error: write after end
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/contentscript.js:19:30103
  at y.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/contentscript.js:19:30166)
  at i.d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/contentscript.js:10:75624)
  at a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/contentscript.js:10:32944)
  at U (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/contentscript.js:10:69334)
  at F (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/contentscript.js:10:69064)
  at B.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/contentscript.js:10:69664)
  at i._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/contentscript.js:10:35416)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/contentscript.js:10:35212

**Comment by mdo6180** [comment]
it turns out this error is caused by metamask. https://community.metamask.io/t/provider-not-getting-connected/27309/11

**Comment by mdo6180** [comment]
resolution: either disable metamask extension on chrome, or use safari for development. i'm going to use safari from now on.
